CREATE TABLE IF NOT EXISTS usuario (
	id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(60) NOT NULL,
    nome VARCHAR(60) NOT NULL,
    senha VARCHAR(400) NOT NULL,
    PRIMARY KEY (id)

)CHARSET = utf8;

CREATE TABLE IF NOT EXISTS receita(
	id INT AUTO_INCREMENT NOT NULL,
    usuarioId INT NOT NULL,
    nome VARCHAR(70) NOT NULL,
	valor FLOAT NOT NULL,
	data DATE NOT NULL,
	descricao VARCHAR(70) NULL ,
	status TINYINT(1) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (usuarioId) REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS meta(

	id INT NOT NULL AUTO_INCREMENT,
	usuarioId INT NOT NULL,
    nome VARCHAR(60) NOT NULL,
	data DATE NOT NULL,
	valor FLOAT NOT NULL,
	descrição VARCHAR(60)  NULL,
	juros FLOAT NOT NULL,
    
	PRIMARY KEY(id),
    FOREIGN KEY (usuarioId) REFERENCES usuario(id)

);

CREATE TABLE IF NOT EXISTS despesa(

	id INT NOT NULL AUTO_INCREMENT,
	usuarioId INT NOT NULL,
    nome VARCHAR(60) NOT NULL,
	valor FLOAT NOT NULL,
	nivel INT NOT NULL,
	periodo DATE NULL,
	data DATE NOT NULL,
	descricao VARCHAR(70) NOT NULL,
	tipo INT NOT NULL,
	PRIMARY KEY(id),
    FOREIGN KEY(usuario) REFERENCES usuario(id)
)